# DSP - Aufgabenblatt 4
#### FHNW - HS2019

## *NumPy*

Schreiben Sie, wo immer möglich und sinnvoll, für die Umsetzung der Aufgabenstellungen Funktionen. Führen Sie die Funktionen mittels `%timeit` aus. Versuchen Sie eine effiziente Implementierung zu finden.

### Aufgabe 1 - Kurzaufgaben

Erzeugen Sie für die folgenden Kurzaufgaben jeweils die notwendindigen *arrays*. Falls nicht genauer spezifiziert, erzuegen sie *arrays* mit ganzzahligen Zufallszahlen auf dem Intervall $[0, 9]$ mittels `np.random.randint`.

In [1]:
import numpy as np

1. Erzeugen Sie einen Vektor der Länge 10, mit überall Nullen, ausser bei Index 5. Hier soll der Wert 5 sein.

In [2]:
x = np.zeros(10,)
x[5] = 5
x

array([ 0.,  0.,  0.,  0.,  0.,  5.,  0.,  0.,  0.,  0.])

2. Drehen Sie die Reihenfolge der Elemente eines *arrays* um.

In [3]:
x = np.arange(10)[::-1]
x

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

3. Geben Sie den Index desjenigen Wertes eines *arrays* zurück, welcher einer zu wählenden Zahl am nächsten ist.

In [4]:
x = np.arange(0,100, 13)

In [5]:
x

array([ 0, 13, 26, 39, 52, 65, 78, 91])

In [6]:
TARGET = 44
idx = np.argmin(np.abs(x - TARGET))
idx

3

4. Erzeugen Sie ein *array* der Grösse $(3 \times 3)$ mit den Werten $[0, 8]$.

In [7]:
np.arange(0,9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

5. Geben Sie den benötigten Speicherplatz eines *arrays* aus, sowie eine einzelnen Elements.

In [8]:
# total memory size in bytes
x.nbytes

64

In [9]:
# memory size of one item
x.itemsize

8

In [10]:
# number of items
x.size

8

6. Erzeugen Sie ein $(3 \times 3 \times 3)$ *array* mit gleichverteilten Zufallszahlen auf dem Intervall $[0, 5]$.

In [54]:
np.random.uniform(5, size=(3,3,3))

array([[[ 2.78374089,  1.20038194,  4.40076396],
        [ 1.26603754,  1.16692713,  3.94576916],
        [ 2.60719881,  2.0058934 ,  1.06460784]],

       [[ 3.02175128,  4.13265841,  3.22125399],
        [ 3.41393439,  3.60551615,  3.69624946],
        [ 4.75399812,  1.27955944,  3.9747639 ]],

       [[ 4.85882551,  2.76591781,  3.25666218],
        [ 3.96549835,  2.29935359,  1.12946751],
        [ 4.83246529,  1.35745407,  4.79967389]]])

7. Erzeugen Sie ein *array* der Grösse $(5 \times 5)$ mit den Elementen $[1,2,3,4,]$ auf der ersten unteren Nebendiagonalen.

In [55]:
np.diagflat([[1,2],[3,4]], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [12]:
np.diag(np.arange(1, 5), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

8. Erzeugen Sie ein *array* der Grösse $(8 \times 8)$ und füllen Sie es mit einem Schachrettmuster der Zahlen $[0, 1]$.

In [13]:
x = np.zeros((8,8))
x[::2, ::2] = 1
x[1::2, 1::2] = 1
x

array([[ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.]])

9. Erzeugen Sie zwei *arrays* gleicher Grösse gefüllt mit ganzzahligen Zufallszahlen und finden Sie die Indices zu jenen Zellen, welche übereinstimmende Zahlen enthalten.  

    Wie können Sie überprüfen, ob die *arrays* gleich sind?

In [14]:
x = np.random.randint(10, size=(100))
y = np.random.randint(10, size=(100))

In [15]:
idx = np.where(x == y)[0]
idx

array([ 0,  8, 25, 32, 37, 48, 58, 59, 75, 88, 92])

In [16]:
x[idx]

array([0, 4, 9, 6, 5, 3, 4, 4, 4, 3, 9])

In [17]:
y[idx]

array([0, 4, 9, 6, 5, 3, 4, 4, 4, 3, 9])

In [18]:
# comparison of the entire array
np.array_equal(x, y)

False

10. Ziehen Sie den Mittelwert sämtlicher Spalten von den Elementen jener Spalte ab.

In [19]:
X = np.random.randint(10, size=(10,10))
X

array([[8, 0, 1, 5, 5, 1, 2, 0, 7, 4],
       [2, 2, 4, 0, 8, 4, 3, 6, 9, 8],
       [0, 7, 0, 2, 1, 2, 8, 3, 7, 3],
       [7, 4, 5, 4, 3, 1, 2, 6, 0, 4],
       [9, 7, 3, 4, 6, 2, 6, 0, 9, 3],
       [9, 2, 1, 2, 6, 5, 8, 2, 6, 7],
       [3, 8, 0, 3, 6, 8, 0, 5, 1, 2],
       [1, 1, 7, 5, 6, 6, 2, 2, 6, 8],
       [9, 4, 9, 8, 2, 3, 9, 7, 5, 7],
       [5, 1, 1, 6, 5, 9, 7, 0, 2, 9]])

In [20]:
X - X.mean(axis=0)

array([[ 2.7, -3.6, -2.1,  1.1,  0.2, -3.1, -2.7, -3.1,  1.8, -1.5],
       [-3.3, -1.6,  0.9, -3.9,  3.2, -0.1, -1.7,  2.9,  3.8,  2.5],
       [-5.3,  3.4, -3.1, -1.9, -3.8, -2.1,  3.3, -0.1,  1.8, -2.5],
       [ 1.7,  0.4,  1.9,  0.1, -1.8, -3.1, -2.7,  2.9, -5.2, -1.5],
       [ 3.7,  3.4, -0.1,  0.1,  1.2, -2.1,  1.3, -3.1,  3.8, -2.5],
       [ 3.7, -1.6, -2.1, -1.9,  1.2,  0.9,  3.3, -1.1,  0.8,  1.5],
       [-2.3,  4.4, -3.1, -0.9,  1.2,  3.9, -4.7,  1.9, -4.2, -3.5],
       [-4.3, -2.6,  3.9,  1.1,  1.2,  1.9, -2.7, -1.1,  0.8,  2.5],
       [ 3.7,  0.4,  5.9,  4.1, -2.8, -1.1,  4.3,  3.9, -0.2,  1.5],
       [-0.3, -2.6, -2.1,  2.1,  0.2,  4.9,  2.3, -3.1, -3.2,  3.5]])

11. Wie können Sie zwei Zeilen eines zwei-dimensionalen *arrays* vertauschen?

In [57]:
X = np.random.randint(10, size=(3, 5))
X

array([[8, 4, 3, 3, 3],
       [0, 2, 0, 3, 9],
       [9, 0, 9, 9, 1]])

In [58]:
X[[0, 1]] = X[[1,0]]
X

array([[0, 2, 0, 3, 9],
       [8, 4, 3, 3, 3],
       [9, 0, 9, 9, 1]])

12. Wie können Sie den Wert eines *boolean arrays* negieren?

In [59]:
b = X > 3
b

array([[False, False, False, False,  True],
       [ True,  True, False, False, False],
       [ True, False,  True,  True, False]], dtype=bool)

In [60]:
np.logical_not(b)

array([[ True,  True,  True,  True, False],
       [False, False,  True,  True,  True],
       [False,  True, False, False,  True]], dtype=bool)

In [62]:
np.invert?

13. Berechnene Sie das Produkt eines Vektors mit einer Matrix, welche bloss $2$-en auf der Diagnolen hat.  
    Messen Sie die Länge des Vektors vor und nach der Transformation. Was stellen Sie fest?

In [63]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

In [25]:
v = np.array([2,3,4])
M = 2*np.eye(3)

In [64]:
M.dot(v)

array([ 4.,  6.,  8.])

In [65]:
np.linalg.norm(v)

5.3851648071345037

In [66]:
np.linalg.norm(M.dot(v))

10.770329614269007